title: JAKE EIDE # your name here
logo: "/images/Jake_Small_051623.jpeg?raw=true" # your photo here
description: > # your text below
  <br><br>
  Thank you for visiting my portfolio of Python projects.
  <br><br>  
  In August of 2021, I completed UT Austin's <a href="https://eportfolio.greatlearning.in/jake-eide" target="_blank">Post Graduate Program in Data Science and Business Analytics</a>. 
  <br><br>
  The projects shown here were completed as part of this program.
  <br><br>
  <a href = "mailto: jacobeide@gmail.com">jacobeide@gmail.com</a>
theme: jekyll-theme-minimal
