title: Jake Eide # your name (or website title) here
logo: "/images/Jake_090921.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  In August of 2021, I completed UT Austin's <a href="https://eportfolio.greatlearning.in/jake-eide" target="_blank">Post Graduate Program in Data Science and Business Analytics</a>. 
  <br><br>
  This page is my portfolio of the Python projects completed in this program.
  <br><br>
  
theme: jekyll-theme-minimal
