title: Jake Eide # your name here
logo: "/images/Jake_090921.png?raw=true" # your photo here
description: > # your text below
  <br><br>
  In August of 2021, I completed UT Austin's <a href="https://eportfolio.greatlearning.in/jake-eide" target="_blank">Post Graduate Program in Data Science and Business Analytics</a>. 
  <br><br>
  The projects shown here were completed as part of this program.
  <br><br>
theme: jekyll-theme-minimal
